release-date = "2022-02-27"

[[entries]]
id = "97d9bcfa-7685-45cb-bf29-65f4bfbdbd1e"
type = "fix"
description = "support more assignment operators like `+=`, `-=`, etc. as well as `and` and `or` binary operators"
author = "@NiklasRosenstein"
issues = [
  "https://github.com/NiklasRosenstein/craftr-dsl/issues/7"
]
