# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push: { branches: [ "develop" ], tags: [ "*" ] }
  pull_request: { branches: [ "develop" ] }

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.x"]
    steps:
    - uses: actions/checkout@v2
    - uses: NiklasRosenstein/slap@gha/install/v1
      with: { version: '>=1.4.5' }
    - uses: actions/setup-python@v2
      with: { python-version: "${{ matrix.python-version }}" }
    - run: slap install --no-venv-check -v
    - run: slap test

  update-pr-numbers:
    if: github.event_name == 'pull_request'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: NiklasRosenstein/slap@gha/changelog/update/v1

  build-documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: NiklasRosenstein/slap@gha/install/v1
      with: { version: '>=1.4.5' }
    - run: pip install -r docs/requirements.txt
    - run: cd docs && novella
    - uses: JamesIves/github-pages-deploy-action@4.1.4
      if: github.ref == 'refs/heads/develop'
      with:
        branch: gh-pages
        folder: docs/_site
        ssh-key: ${{ secrets.DEPLOY_KEY }}
